include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - avoid_print
    - constant_identifier_names
    - prefer_final_locals
    - prefer_final_in_for_each

analyzer:
  errors:
    todo: ignore
    import_of_legacy_library_into_null_safe: ignore
    # ignore those until we are completely nullsafe
    invalid_null_aware_operator: ignore
    unnecessary_null_comparison: ignore
  exclude:
    - example/main.dart
    # needed until crypto packages upgrade
    - lib/src/database/database.g.dart
