name: famedlysdk
description: Matrix Dart SDK
version: 0.0.1
author: Famedly GmbH <info@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.0
  mime: ^1.0.0
  canonical_json: ^1.0.0
  markdown: ^4.0.0
  html_unescape: ^1.0.2
  moor: ^4.0.0
  random_string: ^2.1.0
  encrypt: ^5.0.0-beta.1
  crypto: ^3.0.0
  base58check: ^2.0.0
  olm: ^2.0.0
  matrix_file_e2ee:
    git:
      url: https://gitlab.com/famedly/libraries/matrix_file_e2ee.git
      ref: nullsafety
  isolate: ^2.0.3
  logger: ^1.0.0
  matrix_api_lite: ^0.2.4
  pointycastle: ^3.0.0-nullsafety.2

dev_dependencies:
  test: ^1.15.7
  coverage: ">=0.15.0 <2.0.0"
  moor_generator: ^4.0.0
  build_runner: ^1.11.1
  pedantic: ^1.11.0
  dapackages: ^1.4.0
  #flutter_test: {sdk: flutter}

dependency_overrides:
  args: ^2.0.0
