name: famedlysdk
description: Matrix SDK for the famedly talk app written in dart.
version: 0.0.1
author: Zender & Kurtz GbR <p.kurtz@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2
  mime: ^0.9.7
  canonical_json: ^1.0.0
  markdown: ^3.0.0
  html_unescape: ^1.0.2
  moor: ^3.4.0
  random_string: ^2.1.0
  encrypt: ^4.1.0
  crypto: ^2.1.5
  base58check: ^1.0.1
  password_hash: ^2.0.0
  olm: ^1.2.1
  matrix_file_e2ee: ^1.0.5
  isolate: ^2.0.3
  logger: ^0.9.4
  matrix_api_lite: ^0.1.6

dev_dependencies:
  test: ^1.15.7
  test_coverage: ^0.5.0
  moor_generator: ^3.4.1
  build_runner: ^1.10.13
  pedantic: ^1.9.2
  dapackages: ^1.4.0

  #flutter_test:
  #  sdk: flutter
