name: matrix_api_lite
description: Dead simple data model for the matrix.org client-server API.
version: 0.3.0
homepage: https://famedly.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.13.0
  mime: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.4
