name: famedlysdk
description: Matrix SDK for the famedly talk app written in dart.
version: 0.0.1
author: Zender & Kurtz GbR <p.kurtz@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  mime_type: ^0.3.0
  canonical_json: ^1.0.0
  image: ^2.1.4
  markdown: ^2.1.3
  html_unescape: ^1.0.1+3
  moor: ^3.0.2
  random_string: ^2.0.1

  olm:
    git:
      url: https://gitlab.com/famedly/libraries/dart-olm.git
      ref: 2ef8828859e0c4f6064038e45d89be3e46f8013c

  matrix_file_e2ee:
    path: /home/sorunome/repos/famedly/matrix_file_e2ee
#    git:
#      url: https://gitlab.com/famedly/libraries/matrix_file_e2ee.git
#      ref: 1.x.y

dev_dependencies:
  test: ^1.0.0
  moor_generator: ^3.0.0
  build_runner: ^1.5.2
  pedantic: ^1.9.0 # DO NOT UPDATE AS THIS WOULD CAUSE FLUTTER TO FAIL
  moor_ffi: ^0.5.0
