name: famedlysdk
description: Matrix SDK for the famedly talk app written in dart.
version: 0.0.1
author: Zender & Kurtz GbR <p.kurtz@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  mime_type: ^0.2.4
  intl: ^0.16.0

  json_annotation: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.5.2
  json_serializable: ^3.0.0

  pedantic: ^1.5.0 # DO NOT UPDATE AS THIS WOULD CAUSE FLUTTER TO FAIL
flutter: