name: famedlysdk
description: Matrix SDK for the famedly talk app written in dart.
version: 0.0.1
author: Zender & Kurtz GbR <p.kurtz@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  mime_type: ^0.2.4
  canonical_json: ^1.0.0

  olm:
    git:
      url: https://gitlab.com/famedly/libraries/dart-olm.git
      ref: bbc7ce10a52be5d5c10d2eb6c3591aade71356e2

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.5.2
  pedantic: ^1.5.0 # DO NOT UPDATE AS THIS WOULD CAUSE FLUTTER TO FAIL
