name: matrix_api_lite
description: Dead simple data model for the matrix.org client-server API.
version: 0.1.6
homepage: https://famedly.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  logger: ^0.9.4
  mime: ^0.9.7

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
