name: famedlysdk
description: Matrix Dart SDK
version: 0.0.1
author: Famedly GmbH <info@famedly.com>
homepage: https://famedly.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.0
  mime: ^1.0.0
  canonical_json: ^1.0.0
  markdown: ^3.0.0
  html_unescape: ^1.0.2
  moor: ^4.0.0
  random_string: ^2.1.0
  encrypt: ^4.1.0
  crypto: ^2.1.5
  base58check: ^1.0.1
  password_hash: ^2.0.0
  olm: ^2.0.0
  matrix_file_e2ee: ^1.1.0
  isolate: ^2.0.3
  logger: ^1.0.0
  matrix_api_lite: ^0.2.4

dev_dependencies:
  test: ^1.15.7
  coverage: ">=0.15.0 <2.0.0"
  moor_generator: ^4.0.0
  build_runner: ^1.11.1
  pedantic: ^1.11.0
  dapackages: ^1.4.0
  #flutter_test: {sdk: flutter}

dependency_overrides:
  # needed until crypto packages upgrade
  convert: ^3.0.0
