[book]
title = "Famedly Matrix SDK Documentation"
description = "Famedly Matrix SDK Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
